TOOL_ROOTS := libnumaprof-pintool

HWLOC_PREFIX=$(HOME)/usr

CST_SRC=$(SRCDIR)/../..
CST_BUILD=$(CST_SRC)/build
CST_CFLAGS=-I$(CST_SRC)/src -I$(CST_BUILD)/src -DUSE_PIN_LOCKS -I$(CST_SRC)/extern-deps/from-numactl -O3 -g
#CST_LSFLAGS=-Wl,-rpath=$(CST_BUILD)/src $(CST_BUILD)/src/libnumaprof.so 

OBJS=$(OBJDIR)numaprof-debug$(OBJ_SUFFIX)\
     $(OBJDIR)numaprof-page-table$(OBJ_SUFFIX)\
     $(OBJDIR)numaprof-move-pages$(OBJ_SUFFIX)\
     $(OBJDIR)numaprof-helper$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-process-tracker$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-thread-tracker$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-json-state$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-json-convert$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-stats$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-stack$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-malloc-tracker$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-malt-debug$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-malt-formatted-message$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-malt-linux-proc-map$(OBJ_SUFFIX)\
	 $(OBJDIR)numaprof-malt-symbol-registry$(OBJ_SUFFIX)\
     $(OBJDIR)numaprof-numa-topo$(OBJ_SUFFIX)

# Build the intermediate object file.
$(OBJDIR)libnumaprof-pintool$(OBJ_SUFFIX): $(SRCDIR)/numaprof.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-debug$(OBJ_SUFFIX): $(SRCDIR)/../../src/Debug.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-page-table$(OBJ_SUFFIX): $(SRCDIR)/../../src/PageTable.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)
	
$(OBJDIR)numaprof-stack$(OBJ_SUFFIX): $(SRCDIR)/../../src/Stack.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-helper$(OBJ_SUFFIX): $(SRCDIR)/../../src/Helper.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-process-tracker$(OBJ_SUFFIX): $(SRCDIR)/../../src/ProcessTracker.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-thread-tracker$(OBJ_SUFFIX): $(SRCDIR)/../../src/ThreadTracker.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-numa-topo$(OBJ_SUFFIX): $(SRCDIR)/../../src/NumaTopo.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)
	
$(OBJDIR)numaprof-stats$(OBJ_SUFFIX): $(SRCDIR)/../../src/Stats.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-malloc-tracker$(OBJ_SUFFIX): $(SRCDIR)/../../src/MallocTracker.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-move-pages$(OBJ_SUFFIX): $(SRCDIR)/../../extern-deps/from-numactl/MovePages.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-json-state$(OBJ_SUFFIX): $(SRCDIR)/../../extern-deps/from-htopml/json/JsonState.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-json-convert$(OBJ_SUFFIX): $(SRCDIR)/../../extern-deps/from-htopml/json/ConvertToJson.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-malt-debug$(OBJ_SUFFIX): $(SRCDIR)/../../extern-deps/from-malt-v2/Debug.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-malt-formatted-message$(OBJ_SUFFIX): $(SRCDIR)/../../extern-deps/from-malt-v2/FormattedMessage.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-malt-linux-proc-map$(OBJ_SUFFIX): $(SRCDIR)/../../extern-deps/from-malt-v2/LinuxProcMapReader.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

$(OBJDIR)numaprof-malt-symbol-registry$(OBJ_SUFFIX): $(SRCDIR)/../../extern-deps/from-malt-v2/SymbolRegistry.cpp 
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $< $(CST_CFLAGS)

# Build the tool as a dll (shared object).
$(OBJDIR)libnumaprof-pintool$(PINTOOL_SUFFIX): $(OBJDIR)libnumaprof-pintool$(OBJ_SUFFIX) $(OBJS)
	$(LINKER) $(TOOL_LDFLAGS_NOOPT) $(LINK_EXE)$@ $^ $(TOOL_LPATHS) $(TOOL_LIBS) $(CST_LSFLAGS) 
