build_and_test:
  script:
  - ls -la
  - rm -rfv build testinstall
  - mkdir build
  - cd build
  - if [ -d /opt/pin-3.2-81205-gcc-linux ]; then ../configure --enable-debug --prefix="$PWD/../testinstall" --with-pintool=/opt/pin-3.2-81205-gcc-linux; else cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$PWD/../testinstall; fi
  - make
  - make test
  - make install
