language: cpp

compiler:
  - gcc

before_install:
   - sudo apt-get install -y node libnuma-dev libqt5webkit5-dev
#  - pip install --user cpp-coveralls

script: 
  - mkdir -p build 
  - cd build 
  - ../configure --enable-debug --enable-gcc-coverage --disable-webview --without-pintool
  - make 
#  - make test

#after_success:
#  - if [ "$CXX" == "g++" ]; then coveralls -r ../ -e src/tests --gcov-options '\-lp'; fi
